### ISSUE TITLE
my persian dataset isnt work true after traning

### ISSUE THREAD

**Issue by ohadianoush** [kan-bayashi/ParallelWaveGAN#116]
hi,
i create my csv file with (229 lines and its 229 wavs) i know its not enough for quality .
and i replaced my data with LJSpeech downloads data.

after training i use this code for text to speech :

https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb#scrollTo=9gGRzrjyudWF

its work very fine by English, but now by my Persian dataset , its create a **weird voice** that isn't like a Persian language :

Input your favorite sentencne in English!
result:
که چقدر از اینکه پیششون نبود ولشون کرده بوده ناراحت بوده
Cleaned text: KHH CHQDR Z YNKHH PYSHSHWN NBWD WLSHWN KHRDH BWDH NRHT BWDH
RTF = 0.220197

i must do any change in parallelwavegan or ljspeech config file for persian language? or any change to this script :
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb#scrollTo=9gGRzrjyudWF

because its write (Input your favorite sentencne in **English**!)

note: this is amost true :(KHH CHQDR Z YNKHH PYSHSHWN NBWD WLSHWN KHRDH BWDH NRHT BWDH) but voice isnt read this!
note2:this paragraph exist in my dataset (که چقدر از اینکه پیششون نبود ولشون کرده بوده ناراحت بوده)

**Comment by kan-bayashi** [comment]
E2E-TTS model consists of two types networks:

1. Text2Mel
2. Mel2Wav (=vocoder, this repository)

Text2Mel model converts text sequence into mel spectrogram, which is basically language-dependent. Therefore, if you want to generate Persian language speech, you need to train not only the vocoder but also text2mel models (such as Tactoron 2, Transformer).

**Comment by ohadianoush** [comment]
ok, tnx a going to do this :+1:

**Comment by ohadianoush** [comment]
sorry could you please guide me for finding python one for Text2Mel in github

**Comment by kan-bayashi** [comment]
You can try our ESPnet. But note that to train the Text2Mel is more difficult than the vocoder since it requires at least several hours data (over 10 hours is better) if you want to train from scratch. For example, LJSpeech contains about 24 hours of speech.
If you do not have enough training data, it is better to use speaker adaptation with pretrained model. Recently several researchers tried to perform adaptation for different language. These kinds of research will help you. You can find the paper in the latest Interspeech proceedings.

**Comment by ohadianoush** [comment]
thanks a lot :+1:
