### ISSUE TITLE
Why not set `aux_context_window` for melgan?

### ISSUE THREAD

**Issue by poor1017** [kan-bayashi/ParallelWaveGAN#190]
Hi @kan-bayashi 

Thanks a lot for your last reply. This time I  have another doubt.

I find `aux_context_window` this param in all pwg config, but not in any melgan config. I think `aux_context_window` is also suitable for melgan training. Is there any other consideration for this (not add the param in melgan config)?

Thank you!

**Comment by kan-bayashi** [comment]
In the case of MelGAN implementation, I followed the official implementation.
Hence, I did not add it, but as you mentioned, it can be added instead of simple padding here.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/bb32b19f9ccb638de670f8b8d3a1dfed13ecf1c3/parallel_wavegan/models/melgan.py#L71-L72
So consequently, there is no special reason not to add `aux_context_window`.

**Comment by poor1017** [comment]
Got it.
